services:
  postgres:
    image: postgres:18
    container_name: postgres-query-optimization
    restart: unless-stopped

    environment:
      POSTGRES_DB: optimization_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sql/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql

volumes:
  postgres_data: